<?php

namespace k1app\table_config\defaults;

class admin_rol extends base_all_roles {

    const BOARD_READ_NAME = NULL;
    const CONTROLLER_ALLOWED_LEVELS = ['god', 'admin'];

    /**
     * ALLOWED LEVELS
     */
    const BOARD_CREATE_ALLOWED_LEVELS = self::CONTROLLER_ALLOWED_LEVELS;
    const BOARD_READ_ALLOWED_LEVELS   = self::CONTROLLER_ALLOWED_LEVELS;
    const BOARD_UPDATE_ALLOWED_LEVELS = self::CONTROLLER_ALLOWED_LEVELS;
    const BOARD_DELETE_ALLOWED_LEVELS = self::CONTROLLER_ALLOWED_LEVELS;
    const BOARD_EXPORT_ALLOWED_LEVELS = self::CONTROLLER_ALLOWED_LEVELS;
    const BOARD_LIST_ALLOWED_LEVELS   = self::CONTROLLER_ALLOWED_LEVELS;
}
